site_name: Inteligência Artificial
theme:
  logo: assets/logoBranco.png
  favicon: assets/logo.png
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.integrate
extra_css:
  - stylesheets/styles.css
dev_addr: "0.0.0.0:8000"

nav:
  - Sobre: index.md
  - Introdução à Inteligência Artificial: introIA/introIA.md
  - Resolução de problemas por busca: introIA/introIA1.md
  - Problemas de satisfação de condições: introIA/introIA2.md
  - Agentes lógicos: introIA/introIA3.md
  - Quantificação de incertezas e redes Bayesianas: introIA/introIA4.md
