docs_dir: "docs"
site_name: Inteligência Artificial
theme:
  logo: assets/logoBranco.png
  favicon: assets/logo.png
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.integrate
extra_css:
  - stylesheets/styles.css
dev_addr: "0.0.0.0:8080"

nav:
  - Sobre: index.md
  - Introdução à Inteligência Artificial:
      - Histórico: modulo1/historico.md
      - Inteligência Artificial: modulo1/IA.md
      - Limitações, riscos e ética: modulo1/limitacoes.md
      - AI Index Report 2024: modulo1/AI-Index-2024.md
      - Referências: modulo1/referencias.md
  #- Resolução de problemas por busca:
  #- Problemas de satisfação de condições: 
  #- Agentes lógicos:
  #- Quantificação de incertezas e redes Bayesianas: 

repo_url: https://github.com/sabrinaberno/InteligenciaArtificial
repo_name: sabrinaberno.github.io/InteligenciaArtificial/