docs_dir: "docs"
site_name: Inteligência Artificial
theme:
  logo: assets/logoBranco.png
  favicon: assets/logo.png
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.integrate
extra_css:
  - stylesheets/styles.css
dev_addr: "0.0.0.0:8080"

nav:
  - Sobre: index.md
  - Introdução à Inteligência Artificial:
    - Histórico: modulo1/historico.md
    - Inteligência Artificial: modulo1/IA.md
    - Limitações, riscos e ética: modulo1/limitacoes.md
    - AI Index Report 2024: modulo1/AI-Index-2024.md
    - Agentes Inteligentes: modulo1/agentes.md
    - Referências: modulo1/referencias.md
  - Resolução de problemas por busca:
    - Agente de soluções de problemas: modulo2/agente.md
    - Problemas de malha aberta e de malha fechada: modulo2/malha.md
    - Algoritmos de Busca: modulo2/busca.md
    - Implementação de Busca: modulo2/algoritmos.md
    - Funções Heurísticas: modulo2/heuristica.md
    - Ambientes Complexos: modulo2/complexos.md
    - Algoritmos Genéticos: modulo2/geneticos.md
    - Referências: modulo2/referencias.md
  - Problemas de satisfação de condições: 
    - Atômica vs. Fatorada: modulo3/AtomicaFatorada.md
    - Problemas de Satisfação de Condições: modulo3/satisfacao.md
    - Tipos de Restrições: modulo3/restricoes.md
    - Consistência: modulo3/consistencia.md
    - Algoritmos: modulo3/algoritmos.md
    - Estruturas de Problemas: modulo3/problemas.md
    - Implementação dos Algoritmos: modulo3/implementacao
    - Referências: modulo3/referencias.md
  #- Agentes lógicos:
  #- Quantificação de incertezas e redes Bayesianas: 

repo_url: https://github.com/sabrinaberno/InteligenciaArtificial
repo_name: sabrinaberno.github.io/InteligenciaArtificial/